// openGym's exercise catalogue as part of Gymmie's default exercise library.
// Generated by member-app/scripts/export-gymmie-library.mjs; ids are `og:<openGym id>` so a plan can
// point at an exercise the member app (which carries the same catalogue) resolves exactly.
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const raw = JSON.parse(readFileSync(resolve(here, '..', 'data', 'opengym_exercises.json'), 'utf8'));

export const OPENGYM_EXERCISES = raw.rows.map(([id, name, category, equipment, img, eq, kind]) => ({
  id: `og:${id}`, name, category, equipment, builtIn: true, source: 'opengym', image: img ? `exercise-media/still/${img}` : null, clip: img ? `exercise-media/clip/${img.replace(/\.webp$/, '.mp4')}` : null, kind: kind || null, detail: eq || null,
}));
const byId = new Map(OPENGYM_EXERCISES.map((e) => [e.id, e]));
export const openGymExercise = (id) => byId.get(id) ?? null;

/** Adds the picture and animation URLs when the media host is configured (and the operator is licensed to show it). */
export const withImage = (e, base) => {
  const { clip, ...rest } = e;
  return e.image && base ? { ...rest, imageUrl: `${base}/${e.image}`, clipUrl: clip ? `${base}/${clip}` : null } : rest;
};
